In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
iris = pd.read_csv("Iris Flower - Iris.csv")

In [4]:
iris.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [18]:
iris.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn import datasets

In [7]:

iris = datasets.load_iris()


df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target
df['species'] = df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})


print(df.head())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [9]:
iris = df

In [10]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [16]:
X = iris.drop(columns = ["species"])
y = iris ["species"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=42)
random_forest = RandomForestClassifier(random_state = 42)

mlp = MLPClassifier(random_state= 42 ,max_iter=1000)

random_forest.fit(X_train,y_train)
mlp.fit(X_train,y_train)

y_pred_rf = random_forest.predict(X_test)
y_pred_mlp = mlp.predict(X_test)

accuracy_rf = accuracy_score(y_test,y_pred_rf)
accuracy_mlp = accuracy_score(y_test,y_pred_mlp)

print(f"Random Forest Accuracy : {accuracy_rf*100} ")
print(f"MLP accuracy : {accuracy_mlp*100}")

print("Random Forest Confusion Matrix : ")
print(confusion_matrix(y_test,y_pred_rf))
print("Random Forest Classification report : ")
print (classification_report(y_test,y_pred_rf))

print("MLP Confusion Matrix : ")
print(confusion_matrix(y_test,y_pred_mlp))
print("MLP Classification report : ")
print (classification_report(y_test,y_pred_mlp))



Random Forest Accuracy : 100.0 
MLP accuracy : 100.0
Random Forest Confusion Matrix : 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Random Forest Classification report : 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

MLP Confusion Matrix : 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
MLP Classification report : 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1